resolver: lts-18.28

flags: {}

extra-deps:
  - git: http://github.com/DaisukeBekki/JSeM.git
    commit: b725e62dd66cbbb4fe891ee84108d7a398f5dd71
  - git: git@github.com:DaisukeBekki/hasktorch-tools.git
    commit: 936928cdee27e179a5e3775d146046b107b0eba1
  - git: https://github.com/DaisukeBekki/lightblue.git
    commit: b92288d6b19ec1311e17b206e991d78a0ddb0341
  # - /Users/daidohinari/blab/mycode/lightblue

build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true
